### ISSUE TITLE
패키지이름은 소문자로 작성하세요.

### ISSUE THREAD

**Issue by sigmadream** [ks2017748088/ks-web#1]
https://github.com/ks2017748088/ks-web/blob/50b7d17add48978551fddf9f571de01ace5215c7/src/main/java/com/nayoung/app/Controller/IndexController.java#L1

자바의 패키지 이름은 소문자로 작성하세요.

**Comment by naaaaaaaao** [comment]
바꿨습니다 확인부탁드려요.

**Comment by sigmadream** [comment]
수고하셨습니다
